Refactor auth module
spatie-custom/blender pull request #510
Opened 2018-02-09 13:32 UTC by ianrodrigues

This PR is related to the issue (#376).

Is really there a need to have more than one `UserIsAlreadyActivated` class? And do same for events? 🤔

2018-02-09 16:38 UTC, sebastiandedeyne commented
Thanks! I'll review this Monday :)

2018-02-09 17:02 UTC, ianrodrigues commented
ok, any time! :)

2018-02-23 15:28 UTC, sebastiandedeyne requested changes
Awesome! Commented on a typo somewhere.

Before we wrap this up, could you resolve the conflicts, and rename the tables too (`users` and `admnistrators`)?

2018-02-23 15:28 UTC, sebastiandedeyne commented on tests/Browser/Back/PasswordResetTest.php
> +use App\Models\Administrtor;
Looks like there's a typo in this file :)

2018-02-23 15:28 UTC, sebastiandedeyne commented on tests/Browser/Back/PasswordResetTest.php
> +        $user = Administrtor::create([
See above

2018-02-24 21:40 UTC, ianrodrigues commented
Yeah, I can do it next Monday or Tuesday.

2018-06-25 10:01 UTC, closed without merging